name: Upload Playwright Report

description: Upload Playwright HTML Report

inputs:
  artifact-name:
    description: Artifact name
    required: true

runs:
  using: composite

  steps:
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: playwright-report/