name: Setup Playwright

description: Install Node.js, dependencies and Playwright browsers

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps